import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { builtInLocalDefaults, defaultEnvKeys } from "./config.js";

/**
 * Resolve one env key: process.env → project envDefaults → port-derived built-ins.
 * @param {string} key
 * @param {import('./config.js').AgentRuntimeConfig} config
 * @param {NodeJS.ProcessEnv} [env]
 * @returns {string | undefined}
 */
export function resolveEnvValue(key, config, env = process.env) {
  const fromProcess = env[key];
  if (fromProcess !== undefined && fromProcess !== "") return fromProcess;

  const fromProject = config.envDefaults?.[key];
  if (fromProject !== undefined && fromProject !== "") return fromProject;

  const builtIn = builtInLocalDefaults(config)[key];
  if (builtIn !== undefined && builtIn !== "") return builtIn;

  return undefined;
}

/**
 * @param {import('./config.js').AgentRuntimeConfig} config
 * @param {NodeJS.ProcessEnv} [env]
 * @returns {Record<string, string>}
 */
export function resolveEnvMap(config, env = process.env) {
  const keys = config.envKeys?.length ? config.envKeys : defaultEnvKeys(config);
  /** @type {Record<string, string>} */
  const out = {};
  for (const key of keys) {
    const value = resolveEnvValue(key, config, env);
    if (value !== undefined) out[key] = value;
  }
  // Always ensure core Supabase/DB keys exist when using local defaults,
  // even if envKeys omitted them (avoids half-written .env.local).
  for (const key of Object.keys(builtInLocalDefaults(config))) {
    if (out[key] !== undefined) continue;
    const value = resolveEnvValue(key, config, env);
    if (value !== undefined) out[key] = value;
  }
  return out;
}

/**
 * @param {string} projectRoot
 * @param {Record<string, string>} values
 * @param {{ generatorLabel?: string }} [opts]
 * @returns {string} path written
 */
export function writeEnvLocal(projectRoot, values, opts = {}) {
  const path = join(projectRoot, ".env.local");
  const label = opts.generatorLabel || "agent-runtime setup-env";
  const lines = [
    `# Generated by ${label} — safe to regenerate.`,
    `# Values come from environment variables (e.g. Cursor Secrets) when set,`,
    `# otherwise fall back to project envDefaults / local Supabase defaults.`,
    `# Do not commit this file.`,
    "",
  ];
  for (const [key, value] of Object.entries(values)) {
    lines.push(`${key}=${escapeEnvValue(value)}`);
  }
  lines.push("");
  writeFileSync(path, lines.join("\n"), { mode: 0o600 });
  return path;
}

/**
 * @param {string} value
 */
function escapeEnvValue(value) {
  // Unquoted is fine for typical URLs/secrets without spaces/newlines.
  if (/[\s#"']/.test(value) || value.includes("\n")) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Apply resolved values onto process.env for child processes.
 * @param {Record<string, string>} values
 * @param {NodeJS.ProcessEnv} [env]
 */
export function applyResolvedEnv(values, env = process.env) {
  for (const [k, v] of Object.entries(values)) {
    env[k] = v;
  }
}
